config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  match('/recipes/get_random_recipe', {:via => :get, :from => 'recipes#get_random_recipe'})
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  match('/recipes/search', {:via => :get, :to => 'recipes#search_by_ingredients'})
  match('/recipes/:id/add_rating', {:via => :post, :to => 'recipes#add_rating'})
  match('/users/login', {:via => :get, :from => 'devise/sessions#new'})

  resources :ratings
  match('/recipes/:id/add_tag', {:via => :post, :to => 'recipes#add_tag'})
  match('/tags/search', {:via => :get, :to => 'tags#search'})

  resources :tags
  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :title, :presence => true
  validates :author, :presence => true
  validates :ingredients, :presence => true
  validates :instructions, :presence => true

  has_many :tags
  has_many :ratings

  has_attached_file :image, styles: { small: "64x64", medium: "100x100", large: "200x200" }
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }

  def self.all_sorted_by_ratings
    Recipe.all.order("-average_rating asc")
  end

  def self.get_random_unrated_recipe_or_random_recipe
    recipesNotRated = Recipe.where(:average_rating => nil)
    if recipesNotRated.empty?
      Recipe.all.sample
    else
      recipesNotRated.sample
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def search_by_ingredients
    if !params[:recipe_search_string].nil? && !params[:recipe_search_string].empty?
      recipe_search_string = params[:recipe_search_string].strip
      @recipes = Recipe.where(
      "ingredients like '%#{recipe_search_string.capitalize}%' OR ingredients like '%#{recipe_search_string.downcase}%' OR ingredients like '%#{recipe_search_string.upcase}%'  "+
      "OR instructions like '%#{recipe_search_string.capitalize}%' OR instructions like '%#{recipe_search_string.downcase}%' OR instructions like '%#{recipe_search_string.upcase}%' "+
      "OR title like '%#{recipe_search_string.capitalize}%' OR title like '%#{recipe_search_string.downcase}%' OR title like '%#{recipe_search_string.upcase}%' "+
      "OR author like '%#{recipe_search_string.capitalize}%' OR author like '%#{recipe_search_string.downcase}%' OR author like '%#{recipe_search_string.upcase}%' ")
    else
      @recipes = []
    end
  end

  def get_random_recipe
     @recipe = Recipe.all.sample
     respond_to do |format|
       format.html { redirect_to recipes_url }
       format.json { render :show, status: :ok, location: @recipe }
     end
   end

  def index
    @recipes = Recipe.all_sorted_by_ratings
    extraRecipe = Recipe.get_random_unrated_recipe_or_random_recipe
    if !extraRecipe.nil?
      @recipes.unshift(extraRecipe)
    end
  end

  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def add_tag
    @recipe = Recipe.find(params[:id])
    newTag = Tag.new(params[:tag])
    if newTag.valid?
      newTag.save
      @recipe.tags << newTag
      @recipe.save
    end
    render 'show.html.erb'
  end

  def add_rating
    @recipe = Recipe.find(params[:id])
    newRating = Rating.new(params[:rating])
    if newRating.valid?
      newRating.save
      @recipe.ratings << newRating
      @recipe.average_rating = @recipe.ratings.average(:rating)
      @recipe.save
    end
    render 'show.html.erb'
  end


  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def sort
  #   @recipes = Recipe.all.order(average_rating: :desc)
  #   render 'index.html.erb'
  # end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :author, :ingredients, :instructions, :image)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Author</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.title %></td>
          <td><%= image_tag recipe.image.url(:small) %></td>
          <td><%= recipe.author %></td>
          <% if !recipe.average_rating.nil? %>
            <td><%= recipe.average_rating.round(1) %></td>
          <% else%>
            <td><%= "New Recipe!" %></td>
          <% end %>
          <td><%= link_to 'Show', recipe %> |</td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %> |</td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<hr/>

<form action="/recipes/search" method="get">
  <label for="recipe_search_input">Search for:</label>
  <input id="recipe_search_input" type="text" name="recipe_search_string"></input>
  <input type="submit" value="Search"></input>
</form>

<hr/>


<%= link_to 'Back to Homepage', root_path %> |

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back to Homepage', root_path %> |

<%= link_to 'Show Recipes', recipes_path %>

app/views/recipes/search_by_ingredients.html.erb
<h1>Search Recipes</h1>

<form action="/recipes/search" method="get">
  <label for="recipe_search_input">Search for:</label>
  <input id="recipe_search_input" type="text" name="recipe_search_string"></input>
  <input type="submit" value="Search"></input>
</form>

<hr/>

<% if !@recipes.nil? %>
  <% if !@recipes.empty? %>
    <h3>Recipes Found:</h3>
    <% @recipes.each do |recipe| %>
      <p id="search"><%= link_to(recipe.title, recipe) %></p>
    <% end %>
  <% else %>
      <h3>No Recipes Found</h3>
  <% end %>
<% end %>

<%= link_to 'Back', recipes_path %> |
<%= link_to 'Back to Homepage', root_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for(:title, @recipe.title) %>

<h1>
  <strong><%= @recipe.title %></strong>
</h1>

<%= link_to image_tag(@recipe.image.url(:medium)), @recipe.image.url %>

<h3>
    <% if !@recipe.average_rating.nil? %>
      <strong>Rating:</strong>
      <%= @recipe.average_rating.round(1) %>
    <% end %>
</h3>

<form action="/recipes/<%=@recipe.id%>/add_rating" method="post">
  <select id="rating_id" name="rating[rating]">
    <option>Rate It</options>
    <option value="1">1 Star</option>
    <option value="2">2 Stars</option>
    <option value="3">3 Stars</option>
    <option value="4">4 Stars</option>
    <option value="5">5 Stars</option>
  </select>
  <div class="actions">
    <input type="submit" value="Add Rating">
  </div>
</form>



<p>
  <strong>Author:</strong>
  <%= @recipe.author %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p>
  <strong>Tags: </strong>
  <% @recipe.tags.each do |tag| %>
    <%= tag.name %>,
  <% end %>
</p>

<form action="/recipes/<%= @recipe.id %>/add_tag" method="post">
  <div class="field">
    <label for="tag_name">Tag Name</label>
    <input type="text" name="tag[name]" id="tag_name">
  </div>
  <div class="actions">
    <input type="submit" name="commit" value="Add Tag">
  </div>
</form>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %> |
<%= link_to 'Back to Tag index', tags_path %>

app/views/recipes/sort.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.title %></td>
          <td><%= recipe.author %></td>
          <% if !recipe.average_rating.nil? %>
            <td><%= recipe.average_rating.round(1) %></td>
          <% else%>
            <td><%= "Not Rated." %></td>
          <% end %>
          <td><%= link_to 'Show', recipe %> |</td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %> |</td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>



<br>

<%= link_to 'Back to Homepage', root_path %> |

<%= link_to 'New Recipe', new_recipe_path %>