config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  match('/recipes/get_random_recipe', {:via => :get, :from => 'recipes#get_random_recipe'})
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  match('/recipes/search', {:via => :get, :to => 'recipes#search_by_ingredients'})
  match('/recipes/:id/add_rating', {:via => :post, :to => 'recipes#add_rating'})
  match('/users/login', {:via => :get, :from => 'devise/sessions#new'})

  resources :ratings
  match('/recipes/:id/add_tag', {:via => :post, :to => 'recipes#add_tag'})
  match('/tags/search', {:via => :get, :to => 'tags#search'})

  resources :tags
  resources :recipes

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :recipe
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def find_recipe
    @tag = Tag.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
    @tag.recipe = @recipe

    render 'show.html.erb'
  end

  #SEARCH /tags/search
  def search
    if !params[:search_string].nil?
      search_string = params[:search_string].strip
      @tags = Tag.where(:name => search_string)
    end
  end
  # def search
  #   @search_string = params[:search_string]
  #   @search_string = @search_string.strip
  #   if @search_string.valid?
  #     @tags = []
  #   else
  #     @tags.
  # end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show Recipe', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/search.html.erb
<h1>Search for Recipes by Tags</h1>

<form action="/tags/search" method="get">
  <label for="tag_search_input">Tag Name:</label>
  <input id="tag_search_input" type="text" name="search_string"></input>
  <input type="submit" value="Search"></input>
</form>

<hr/>

<% if !@tags.nil? %>
  <% if !@tags.empty? %>
    <h3>Recipes Found:</h3>
    <% @tags.each do |tag| %>
      <p id="search"><%= link_to(tag.recipe.title, tag.recipe) %></p>
    <% end %>
  <% else %>
    <h3>No Recipes Found!</h3>
  <% end %>
<% end %>

<%= link_to 'Recipe List', recipes_path %> |
<%= link_to 'Back to Homepage', root_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for(:name, @tag.name) %>

<h1>
  <strong><%= @tag.name %></strong>
</h1>


<a href="/recipes/<%= @tag.recipe_id %>"><p><strong><%= @tag.recipe.title %></strong></p>
</a>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>